name = "MonotonicSplines"
uuid = "568f7cb4-8305-41bc-b90d-d32b39cc99d1"
version = "0.1.5"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HeterogeneousComputing = "2182be2a-124f-4a91-8389-f06db5907a21"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Adapt = "1, 2, 3, 4"
ChainRulesCore = "1"
ChangesOfVariables = "0.1.3"
Functors = "0.2, 0.3, 0.4"
HeterogeneousComputing = "0.2"
InverseFunctions = "0.1.8"
KernelAbstractions = "0.9"
LinearAlgebra = "1"
julia = "1.10"
